"""init db

Revision ID: 0718c5987d3a
Revises: 
Create Date: 2022-01-19 21:45:31.808664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0718c5987d3a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
