"""alter unique constraints

Revision ID: b050d5acfb47
Revises: 0718c5987d3a
Create Date: 2022-01-19 22:00:49.180857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b050d5acfb47'
down_revision = '0718c5987d3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('binders', schema=None) as batch_op:
        batch_op.drop_constraint('binder_constraints', type_='unique')
        batch_op.create_unique_constraint("id_unique", ['user_id'])
        batch_op.create_unique_constraint("plate_unique", ['plate'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('binders', schema=None) as batch_op:
        batch_op.drop_constraint("id_unique", type_='unique')
        batch_op.drop_constraint("plate_unique", type_='unique')
        batch_op.create_unique_constraint('binder_constraints', ['plate', 'user_id'])

    # ### end Alembic commands ###
