from sqlalchemy import Column, DateTime, Integer, String, Float
from database import Base

class Modem_750(Base):
    __tablename__ = 'modems'

    index = Column(Integer, primary_key=True)
    id = Column(Integer)
    transactionId = Column(String)
    messageEncoding = Column(String)
    messageType = Column(String)
    modemId = Column(String)
    messageId = Column(String)
    dataLength = Column(String)
    gpsTime = Column(DateTime)
    latitude = Column(Float)
    longitude = Column(Float)
    altitude = Column(Float)
    speed = Column(Float)
    direction = Column(Float)
    odometer = Column(Integer)
    hdop = Column(Float)
    satellites = Column(Integer)
    ioStatus = Column(String)
    reserved = Column(String)
    mainPowerVoltage = Column(Float)
    backupBatteryVoltage = Column(Float)
    rtcTime = Column(DateTime)
    posTime = Column(DateTime)
    csq = Column(String)
    mcuMotorRpm = Column(Integer)
    obdSpeed = Column(Integer)
    bmsBatterySoc = Column(Integer)
    mtrOdoData = Column(String)
    keyStatus = Column(String)
    chargingStatus = Column(String)